name: JPEG-XL

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - platform: Linux64
            os: ubuntu-latest
            generator: "Ninja Multi-Config"
            cmakeCommand: "cmake"
          #- platform: MacOS
          #  os: macos-latest
          #  generator: "Ninja Multi-Config"
          #  cmakeCommand: "xcrun cmake"
          #- platform: Win64
          #  os: windows-latest
          #  generator: "Visual Studio 17 2022"
          #  cmakeCommand: "cmake"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: oras-project/setup-oras@v1
      - uses: actions/checkout@v3
        with:
          repository: libjxl/libjxl
          submodules: 'recursive'
      - name: Create build directory
        run: mkdir build
      - name: Configure CMake
        working-directory: build
        run: ${{ matrix.cmakeCommand }} -G "${{ matrix.generator }}" -DBUILD_SHARED_LIBS=ON -DBUILD_TESTING=OFF ..
      - name: Build
        working-directory: build
        run: ${{ matrix.cmakeCommand }} --build . --config Release --target jxl
      # all artifacts are in build/lib/Release
      - name: Upload to B2
        uses: jakejarvis/s3-sync-action@master
        with: 
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: heathdeps
          AWS_ACCESS_KEY_ID: ${{ secrets.B2_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_KEY }}
          AWS_S3_ENDPOINT: ${{ vars.B2_ENDPOINT }}
          SOURCE_DIR: "./build/lib/Release/"
          DEST_DIR: "jxl/${{ matrix.platform }}/${{ github.run_id }}/"
